apiVersion: apps/v1
kind: Deployment
metadata:
  name: argotest6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argotest6
  template:
    metadata:
      labels:
        app: argotest6
    spec:
      containers:
        - name: argotest6
          image: chaitanyapandeygspann/argotest6:1.0.${BUILD_NUMBER}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000