apiVersion: apps/v1
kind: Deployment
metadata:
  name: dssp-apr-10
  labels:
    backstage.io/kubernetes-id: dssp-apr-10
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dssp-apr-10
  template:
    metadata:
      labels:
        app: dssp-apr-10
        backstage.io/kubernetes-id: dssp-apr-10
    spec:
      containers:
        - name: dssp-apr-10
          image: chaitanyapandeygspann/dssp-apr-10:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000