apiVersion: apps/v1
kind: Deployment
metadata:
  name: dssp-may-07-03
  labels:
    backstage.io/kubernetes-id: dssp-may-07-03
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dssp-may-07-03
  template:
    metadata:
      labels:
        app: dssp-may-07-03
        backstage.io/kubernetes-id: dssp-may-07-03
    spec:
      containers:
        - name: dssp-may-07-03
          image: chaitanyapandeygspann/dssp-may-07-03:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000