apiVersion: v1
kind: Service
metadata:
  name: gssp-27-mar-2026-01
spec:
  selector:
    app: gssp-27-mar-2026-01
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer


# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: gssp-27-mar-2026-01-ingress
# spec:
#   ingressClassName: gce
#   rules:
#   - host: gssp-27-mar-2026-01.example.com
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: gssp-27-mar-2026-01
#             port:
#               number: 80
