apiVersion: apps/v1
kind: Deployment
metadata:
  name: dssp-python-test-1
  labels:
    backstage.io/kubernetes-id: dssp-python-test-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dssp-python-test-1
  template:
    metadata:
      labels:
        app: dssp-python-test-1
        backstage.io/kubernetes-id: dssp-python-test-1
    spec:
      containers:
        - name: dssp-python-test-1
          image: chaitanyapandeygspann/dssp-python-test-1:1.0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 5000