apiVersion: apps/v1
kind: Deployment
metadata:
  name: dssp-targetp-72
  namespace: dev
  labels:
    app: dssp-targetp-72
    backstage.io/kubernetes-id: dssp-targetp-72
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dssp-targetp-72
  template:
    metadata:
      labels:
        app: dssp-targetp-72
        backstage.io/kubernetes-id: dssp-targetp-72
        environment: dev
    spec:
      containers:
        - name: dssp-targetp-72
          image: chaitanyapandeygspann/dssp-targetp-72:1.0.3
          ports:
            - containerPort: 5000
          env:
            - name: APP_ENV
              value: "dev"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
