apiVersion: apps/v1
kind: Deployment
metadata:
  name: dssp-apr-10-02
  labels:
    backstage.io/kubernetes-id: dssp-apr-10-02
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dssp-apr-10-02
  template:
    metadata:
      labels:
        app: dssp-apr-10-02
        backstage.io/kubernetes-id: dssp-apr-10-02
    spec:
      containers:
        - name: dssp-apr-10-02
          image: chaitanyapandeygspann/dssp-apr-10-02:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000