apiVersion: v1
kind: Service
metadata:
  name: dssp-python-project
  namespace: dev
  labels:
    backstage.io/kubernetes-id: dssp-python-project
spec:
  selector:
    app: dssp-python-project
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
