apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-sonar-vault-10
  labels:
    backstage.io/kubernetes-id: test-sonar-vault-10
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-sonar-vault-10
  template:
    metadata:
      labels:
        app: test-sonar-vault-10
        backstage.io/kubernetes-id: test-sonar-vault-10
    spec:
      containers:
        - name: test-sonar-vault-10
          image: chaitanyapandeygspann/test-sonar-vault-10:1.0.3
          imagePullPolicy: Always
          ports:
            - containerPort: 3000