apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-python-app
  labels:
    backstage.io/kubernetes-id: flask-python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-python-app
  template:
    metadata:
      labels:
        app: flask-python-app
        backstage.io/kubernetes-id: flask-python-app
    spec:
      containers:
        - name: flask-python-app
          image: chaitanyapandeygspann/flask-python-app:1.0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 3000