apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: basic-jsp-app
  namespace: argocd
  labels:
    app.kubernetes.io/name: basic-jsp-app
spec:
  project: default
  source:
    repoURL: https://github.com/BackstageSSPPoC/k8s-manifests.git
    targetRevision: main
    path: apps/basic-jsp-app
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
