apiVersion: v1
kind: Service
metadata:
  name: basic-jsp-app
spec:
  selector:
    app: basic-jsp-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer


# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: basic-jsp-app-ingress
# spec:
#   ingressClassName: gce
#   rules:
#   - host: basic-jsp-app.example.com
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: basic-jsp-app
#             port:
#               number: 80