apiVersion: v1
kind: Service
metadata:
  name: ssp-sonarqube-24-apr
spec:
  selector:
    app: ssp-sonarqube-24-apr
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer


# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: ssp-sonarqube-24-apr-ingress
# spec:
#   ingressClassName: gce
#   rules:
#   - host: ssp-sonarqube-24-apr.example.com
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: ssp-sonarqube-24-apr
#             port:
#               number: 80
