apiVersion: v1
kind: Service
metadata:
  name: java-sample-app1
spec:
  selector:
    app: java-sample-app1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer


# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: java-sample-app1-ingress
# spec:
#   ingressClassName: gce
#   rules:
#   - host: java-sample-app1.example.com
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: java-sample-app1
#             port:
#               number: 80