apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-6-march
  labels:
    backstage.io/kubernetes-id: demo-6-march
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-6-march
  template:
    metadata:
      labels:
        app: demo-6-march
        backstage.io/kubernetes-id: demo-6-march
    spec:
      containers:
        - name: demo-6-march
          image: chaitanyapandeygspann/demo-6-march:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000