apiVersion: apps/v1
kind: Deployment
metadata:
  name: gssp-test-br-2
  labels:
    backstage.io/kubernetes-id: gssp-test-br-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gssp-test-br-2
  template:
    metadata:
      labels:
        app: gssp-test-br-2
        backstage.io/kubernetes-id: gssp-test-br-2
    spec:
      containers:
        - name: gssp-test-br-2
          image: chaitanyapandeygspann/gssp-test-br-2:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000