apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-test-01
  labels:
    backstage.io/kubernetes-id: vault-test-01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-test-01
  template:
    metadata:
      labels:
        app: vault-test-01
        backstage.io/kubernetes-id: vault-test-01
    spec:
      containers:
        - name: vault-test-01
          image: chaitanyapandeygspann/vault-test-01:1.0.4
          imagePullPolicy: Always
          ports:
            - containerPort: 3000