apiVersion: apps/v1
kind: Deployment
metadata:
  name: gssp-test-a1
  labels:
    backstage.io/kubernetes-id: gssp-test-a1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gssp-test-a1
  template:
    metadata:
      labels:
        app: gssp-test-a1
        backstage.io/kubernetes-id: gssp-test-a1
    spec:
      containers:
        - name: gssp-test-a1
          image: chaitanyapandeygspann/gssp-test-a1:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000