apiVersion: apps/v1
kind: Deployment
metadata:
  name: dssp-test-sharedsonarqube-28
  labels:
    backstage.io/kubernetes-id: dssp-test-sharedsonarqube-28
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dssp-test-sharedsonarqube-28
  template:
    metadata:
      labels:
        app: dssp-test-sharedsonarqube-28
        backstage.io/kubernetes-id: dssp-test-sharedsonarqube-28
    spec:
      containers:
        - name: dssp-test-sharedsonarqube-28
          image: chaitanyapandeygspann/dssp-test-sharedsonarqube-28:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000