apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-python-app
  labels:
    backstage.io/kubernetes-id: demo-python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-python-app
  template:
    metadata:
      labels:
        app: demo-python-app
        backstage.io/kubernetes-id: demo-python-app
    spec:
      containers:
        - name: demo-python-app
          image: chaitanyapandeygspann/demo-python-app:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000