apiVersion: v1
kind: Service
metadata:
  name: demo-python-app
spec:
  selector:
    app: demo-python-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer


# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: demo-python-app-ingress
# spec:
#   ingressClassName: gce
#   rules:
#   - host: demo-python-app.example.com
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: demo-python-app
#             port:
#               number: 80