apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssp-march-18
  labels:
    backstage.io/kubernetes-id: ssp-march-18
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssp-march-18
  template:
    metadata:
      labels:
        app: ssp-march-18
        backstage.io/kubernetes-id: ssp-march-18
    spec:
      containers:
        - name: ssp-march-18
          image: chaitanyapandeygspann/ssp-march-18:1.0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 3000