apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssp-17-march
  labels:
    backstage.io/kubernetes-id: ssp-17-march
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssp-17-march
  template:
    metadata:
      labels:
        app: ssp-17-march
        backstage.io/kubernetes-id: ssp-17-march
    spec:
      containers:
        - name: ssp-17-march
          image: chaitanyapandeygspann/ssp-17-march:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000