# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: dssp-targetp-21
#   namespace: qa
#   labels:
#     app: dssp-targetp-21
#     backstage.io/kubernetes-id: dssp-targetp-21
#     environment: qa
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: dssp-targetp-21
#   template:
#     metadata:
#       labels:
#         app: dssp-targetp-21
#         backstage.io/kubernetes-id: dssp-targetp-21
#         environment: qa
#     spec:
#       containers:
#         - name: dssp-targetp-21
#           image: chaitanyapandeygspann/dssp-targetp-21:1.0.7
#           ports:
#             - containerPort: 5000
#           env:
#             - name: APP_ENV
#               value: "qa"



apiVersion: apps/v1
kind: Deployment
metadata:
  name: dssp-targetp-21
  namespace: qa
  labels:
    app: dssp-targetp-21
    backstage.io/kubernetes-id: dssp-targetp-21
    environment: qa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dssp-targetp-21
  template:
    metadata:
      labels:
        app: dssp-targetp-21
        backstage.io/kubernetes-id: dssp-targetp-21
        environment: qa
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
    spec:
      containers:
        - name: dssp-targetp-21
          image: chaitanyapandeygspann/dssp-targetp-21:1.0.7
          ports:
            - containerPort: 5000
          env:
            - name: APP_ENV
              value: "qa"
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
              ephemeral-storage: "50Mi"
            limits:
              memory: "128Mi"
              cpu: "100m"
              ephemeral-storage: "100Mi"
