apiVersion: v1
kind: Service
metadata:
  name: dssp-jtest-14
  namespace: dev
  labels:
    backstage.io/kubernetes-id: dssp-jtest-14
spec:
  selector:
    app: dssp-jtest-14
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
