apiVersion: apps/v1
kind: Deployment
metadata:
  name: dssp-targetnode-1
  namespace: qat
  labels:
    app: dssp-targetnode-1
    backstage.io/kubernetes-id: dssp-targetnode-1
    environment: qat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dssp-targetnode-1
  template:
    metadata:
      labels:
        app: dssp-targetnode-1
        backstage.io/kubernetes-id: dssp-targetnode-1
        environment: qat
    spec:
      containers:
        - name: dssp-targetnode-1
          image: chaitanyapandeygspann/dssp-targetnode-1:1.0.5
          ports:
            - containerPort: 3000
          env:
            - name: APP_ENV
              value: "qat"