apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: multilang-python
  namespace: undefined
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /multilang-python-undefined(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: multilang-python
                port:
                  number: 80
