apiVersion: v1
kind: Service
metadata:
  name: jay-ssp-2
  namespace: dev
  labels:
    backstage.io/kubernetes-id: jay-ssp-2
spec:
  selector:
    app: jay-ssp-2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
