apiVersion: apps/v1
kind: Deployment
metadata:
  name: dssp-jtest-5
  namespace: dev
  labels:
    app: dssp-jtest-5
    backstage.io/kubernetes-id: dssp-jtest-5
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dssp-jtest-5
  template:
    metadata:
      labels:
        app: dssp-jtest-5
        backstage.io/kubernetes-id: dssp-jtest-5
        environment: dev
    spec:
      containers:
        - name: dssp-jtest-5
          image: chaitanyapandeygspann/dssp-jtest-5:1.0.2
          ports:
            - containerPort: 8080
          env:
            - name: APP_ENV
              value: "dev"
