apiVersion: apps/v1
kind: Deployment
metadata:
  name: dssp-targetp-49
  namespace: dev
  labels:
    app: dssp-targetp-49
    backstage.io/kubernetes-id: dssp-targetp-49
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dssp-targetp-49
  template:
    metadata:
      labels:
        app: dssp-targetp-49
        backstage.io/kubernetes-id: dssp-targetp-49
        environment: dev
    spec:
      containers:
        - name: dssp-targetp-49
          image: chaitanyapandeygspann/dssp-targetp-49:1.0.1
          ports:
            - containerPort: 5000
          env:
            - name: APP_ENV
              value: "dev"
