apiVersion: apps/v1
kind: Deployment
metadata:
  name: soft-launch-test-1
  labels:
    backstage.io/kubernetes-id: soft-launch-test-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soft-launch-test-1
  template:
    metadata:
      labels:
        app: soft-launch-test-1
        backstage.io/kubernetes-id: soft-launch-test-1
    spec:
      containers:
        - name: soft-launch-test-1
          image: chaitanyapandeygspann/soft-launch-test-1:1.0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 3000