apiVersion: apps/v1
kind: Deployment
metadata:
  name: dssp-targetp-31
  namespace: dev
  labels:
    app: dssp-targetp-31
    backstage.io/kubernetes-id: dssp-targetp-31
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dssp-targetp-31
  template:
    metadata:
      labels:
        app: dssp-targetp-31
        backstage.io/kubernetes-id: dssp-targetp-31
        environment: dev
    spec:
      containers:
        - name: dssp-targetp-31
          image: chaitanyapandeygspann/dssp-targetp-31:1.0.4
          ports:
            - containerPort: 5000
          env:
            - name: APP_ENV
              value: "dev"