apiVersion: v1
kind: Service
metadata:
  name: dssp-targetp-1
  namespace: qat
spec:
  selector:
    app: dssp-targetp-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
 


# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: dssp-targetp-1-ingress
# spec:
#   ingressClassName: gce
#   rules:
#   - host: dssp-targetp-1.example.com
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: dssp-targetp-1
#             port:
#               number: 80
