apiVersion: apps/v1
kind: Deployment
metadata:
  name: dssp-targetp-89
  namespace: dev
  labels:
    app: dssp-targetp-89
    backstage.io/kubernetes-id: dssp-targetp-89
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dssp-targetp-89
  template:
    metadata:
      labels:
        app: dssp-targetp-89
        backstage.io/kubernetes-id: dssp-targetp-89
        environment: dev
    spec:
      containers:
        - name: dssp-targetp-89
          image: chaitanyapandeygspann/dssp-targetp-89:1.0.3
          ports:
            - containerPort: 5000
          env:
            - name: APP_ENV
              value: "dev"
            - name: URL_PREFIX
              value: /dssp-targetp-89-dev
          resources:
            requests:
              memory: "384Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
