apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonar-test-4
  labels:
    backstage.io/kubernetes-id: sonar-test-4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonar-test-4
  template:
    metadata:
      labels:
        app: sonar-test-4
        backstage.io/kubernetes-id: sonar-test-4
    spec:
      containers:
        - name: sonar-test-4
          image: chaitanyapandeygspann/sonar-test-4:1.0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 3000