apiVersion: apps/v1
kind: Deployment
metadata:
  name: dssp-targetp-32
  namespace: dev
  labels:
    app: dssp-targetp-32
    backstage.io/kubernetes-id: dssp-targetp-32
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dssp-targetp-32
  template:
    metadata:
      labels:
        app: dssp-targetp-32
        backstage.io/kubernetes-id: dssp-targetp-32
        environment: dev
    spec:
      containers:
        - name: dssp-targetp-32
          image: chaitanyapandeygspann/dssp-targetp-32:1.0.2
          ports:
            - containerPort: 5000
          env:
            - name: APP_ENV
              value: "dev"