apiVersion: apps/v1
kind: Deployment
metadata:
  name: dssp-test-apr-21-03
  labels:
    backstage.io/kubernetes-id: dssp-test-apr-21-03
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dssp-test-apr-21-03
  template:
    metadata:
      labels:
        app: dssp-test-apr-21-03
        backstage.io/kubernetes-id: dssp-test-apr-21-03
    spec:
      containers:
        - name: dssp-test-apr-21-03
          image: chaitanyapandeygspann/dssp-test-apr-21-03:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000