apiVersion: v1
kind: Service
metadata:
  name: jsp-testing-15-may
  namespace: dev
  labels:
    backstage.io/kubernetes-id: jsp-testing-15-may
    environment: dev
spec:
  selector:
    app: jsp-testing-15-may
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
 


# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: jsp-testing-15-may-ingress
# spec:
#   ingressClassName: gce
#   rules:
#   - host: jsp-testing-15-may.example.com
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: jsp-testing-15-may
#             port:
#               number: 80
