apiVersion: v1
kind: Service
metadata:
  name: dssp-gitlab-test-2
  namespace: dev
  labels:
    backstage.io/kubernetes-id: dssp-gitlab-test-2
spec:
  selector:
    app: dssp-gitlab-test-2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
