apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-shared-vault-sonar-28
  labels:
    backstage.io/kubernetes-id: test-shared-vault-sonar-28
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-shared-vault-sonar-28
  template:
    metadata:
      labels:
        app: test-shared-vault-sonar-28
        backstage.io/kubernetes-id: test-shared-vault-sonar-28
    spec:
      containers:
        - name: test-shared-vault-sonar-28
          image: chaitanyapandeygspann/test-shared-vault-sonar-28:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000