apiVersion: apps/v1
kind: Deployment
metadata:
  name: dssp-targetnode-2
  namespace: prod
  labels:
    app: dssp-targetnode-2
    backstage.io/kubernetes-id: dssp-targetnode-2
    environment: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dssp-targetnode-2
  template:
    metadata:
      labels:
        app: dssp-targetnode-2
        backstage.io/kubernetes-id: dssp-targetnode-2
        environment: prod
    spec:
      containers:
        - name: dssp-targetnode-2
          image: chaitanyapandeygspann/dssp-targetnode-2:1.0.2
          ports:
            - containerPort: 3000
          env:
            - name: APP_ENV
              value: "prod"