apiVersion: apps/v1
kind: Deployment
metadata:
  name: gssp-march-18-3
  labels:
    backstage.io/kubernetes-id: gssp-march-18-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gssp-march-18-3
  template:
    metadata:
      labels:
        app: gssp-march-18-3
        backstage.io/kubernetes-id: gssp-march-18-3
    spec:
      containers:
        - name: gssp-march-18-3
          image: chaitanyapandeygspann/gssp-march-18-3:1.0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 3000