apiVersion: apps/v1
kind: Deployment
metadata:
  name: dssp-targetp-6
  namespace: qat
  labels:
    app: dssp-targetp-6
    backstage.io/kubernetes-id: dssp-targetp-6
    environment: qat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dssp-targetp-6
  template:
    metadata:
      labels:
        app: dssp-targetp-6
        backstage.io/kubernetes-id: dssp-targetp-6
        environment: qat
    spec:
      containers:
        - name: dssp-targetp-6
          image: chaitanyapandeygspann/dssp-targetp-6:1.0.1
          ports:
            - containerPort: 5000
          env:
            - name: APP_ENV
              value: "qat"