apiVersion: apps/v1
kind: Deployment
metadata:
  name: dssp-sonar-test-4
  labels:
    backstage.io/kubernetes-id: dssp-sonar-test-4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dssp-sonar-test-4
  template:
    metadata:
      labels:
        app: dssp-sonar-test-4
        backstage.io/kubernetes-id: dssp-sonar-test-4
    spec:
      containers:
        - name: dssp-sonar-test-4
          image: chaitanyapandeygspann/dssp-sonar-test-4:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000