apiVersion: v1
kind: Service
metadata:
  name: dssp-targetp-51
  namespace: dev
  labels:
    backstage.io/kubernetes-id: dssp-targetp-51
spec:
  selector:
    app: dssp-targetp-51
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
