apiVersion: apps/v1
kind: Deployment
metadata:
  name: dssp-targetp-9
  namespace: qa
  labels:
    app: dssp-targetp-9
    backstage.io/kubernetes-id: dssp-targetp-9
    environment: qa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dssp-targetp-9
  template:
    metadata:
      labels:
        app: dssp-targetp-9
        backstage.io/kubernetes-id: dssp-targetp-9
        environment: qa
    spec:
      containers:
        - name: dssp-targetp-9
          image: chaitanyapandeygspann/dssp-targetp-9:1.0.4
          ports:
            - containerPort: 5000
          env:
            - name: APP_ENV
              value: "qa"