apiVersion: v1
kind: Service
metadata:
  name: dssp-python
spec:
  selector:
    app: dssp-python
  ports:
    - protocol: TCP
      port: 80
      targetPort: ${APP_PORTS}
  type: LoadBalancer


# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: dssp-python-ingress
# spec:
#   ingressClassName: gce
#   rules:
#   - host: dssp-python.example.com
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: dssp-python
#             port:
#               number: 80