apiVersion: v1
kind: Service
metadata:
  name: dssp-springpackage-8
  namespace: dev
  labels:
    backstage.io/kubernetes-id: dssp-springpackage-8
spec:
  selector:
    app: dssp-springpackage-8
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
