apiVersion: apps/v1
kind: Deployment
metadata:
  name: gssp-test1
  labels:
    backstage.io/kubernetes-id: gssp-test1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gssp-test1
  template:
    metadata:
      labels:
        app: gssp-test1
        backstage.io/kubernetes-id: gssp-test1
    spec:
      containers:
        - name: gssp-test1
          image: chaitanyapandeygspann/gssp-test1:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000