apiVersion: apps/v1
kind: Deployment
metadata:
  name: dssp-24-apr-mytesting
  labels:
    backstage.io/kubernetes-id: dssp-24-apr-mytesting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dssp-24-apr-mytesting
  template:
    metadata:
      labels:
        app: dssp-24-apr-mytesting
        backstage.io/kubernetes-id: dssp-24-apr-mytesting
    spec:
      containers:
        - name: dssp-24-apr-mytesting
          image: chaitanyapandeygspann/dssp-24-apr-mytesting:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000