apiVersion: v1
kind: Service
metadata:
  name: dssp-24-apr-mytesting
spec:
  selector:
    app: dssp-24-apr-mytesting
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer


# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: dssp-24-apr-mytesting-ingress
# spec:
#   ingressClassName: gce
#   rules:
#   - host: dssp-24-apr-mytesting.example.com
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: dssp-24-apr-mytesting
#             port:
#               number: 80
