apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssp-march-17-2
  labels:
    backstage.io/kubernetes-id: ssp-march-17-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssp-march-17-2
  template:
    metadata:
      labels:
        app: ssp-march-17-2
        backstage.io/kubernetes-id: ssp-march-17-2
    spec:
      containers:
        - name: ssp-march-17-2
          image: chaitanyapandeygspann/ssp-march-17-2:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000