apiVersion: apps/v1
kind: Deployment
metadata:
  name: dssp-sonar-test-3
  labels:
    backstage.io/kubernetes-id: dssp-sonar-test-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dssp-sonar-test-3
  template:
    metadata:
      labels:
        app: dssp-sonar-test-3
        backstage.io/kubernetes-id: dssp-sonar-test-3
    spec:
      containers:
        - name: dssp-sonar-test-3
          image: chaitanyapandeygspann/dssp-sonar-test-3:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000