apiVersion: apps/v1
kind: Deployment
metadata:
  name: dssp-targetp-12
  namespace: dev
  labels:
    app: dssp-targetp-12
    backstage.io/kubernetes-id: dssp-targetp-12
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dssp-targetp-12
  template:
    metadata:
      labels:
        app: dssp-targetp-12
        backstage.io/kubernetes-id: dssp-targetp-12
        environment: dev
    spec:
      containers:
        - name: dssp-targetp-12
          image: chaitanyapandeygspann/dssp-targetp-12:1.0.8
          ports:
            - containerPort: 5000
          env:
            - name: APP_ENV
              value: "dev"