apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dssp-targetp-16-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/BackstageSSPPoC/k8s-manifests.git
    targetRevision: main
    path: apps/dssp-targetp-16/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true