# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: dssp-targetnode-2
#   namespace: argocd
#   labels:
#     app.kubernetes.io/name: dssp-targetnode-2
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/BackstageSSPPoC/k8s-manifests.git
#     targetRevision: main
#     path: apps/dssp-targetnode-2
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: default
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true


apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dssp-targetnode-2-qat
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/BackstageSSPPoC/k8s-manifests.git
    targetRevision: main
    path: apps/dssp-targetnode-2/qat
  destination:
    server: https://kubernetes.default.svc
    namespace: qat
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
