apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dssp-spring-package-git-lab-08-oct-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/BackstageSSPPoC/k8s-manifests.git
    targetRevision: main
    path: apps/dssp-spring-package-git-lab-08-oct/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
