apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-test-1
  labels:
    backstage.io/kubernetes-id: java-test-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-test-1
  template:
    metadata:
      labels:
        app: java-test-1
        backstage.io/kubernetes-id: java-test-1
    spec:
      containers:
        - name: java-test-1
          image: chaitanyapandeygspann/java-test-1:1.0.9
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
