apiVersion: apps/v1
kind: Deployment
metadata:
  name: may-07-01
  labels:
    backstage.io/kubernetes-id: may-07-01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: may-07-01
  template:
    metadata:
      labels:
        app: may-07-01
        backstage.io/kubernetes-id: may-07-01
    spec:
      containers:
        - name: may-07-01
          image: chaitanyapandeygspann/may-07-01:1.0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 3000