apiVersion: apps/v1
kind: Deployment
metadata:
  name: dssp-gitlab-test-1
  namespace: dev
  labels:
    app: dssp-gitlab-test-1
    backstage.io/kubernetes-id: dssp-gitlab-test-1
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dssp-gitlab-test-1
  template:
    metadata:
      labels:
        app: dssp-gitlab-test-1
        backstage.io/kubernetes-id: dssp-gitlab-test-1
        environment: dev
    spec:
      containers:
        - name: dssp-gitlab-test-1
          image: chaitanyapandeygspann/dssp-gitlab-test-1:1.0.5
          ports:
            - containerPort: 5000
          env:
            - name: APP_ENV
              value: "dev"
            - name: URL_PREFIX
              value: /dssp-gitlab-test-1-dev
          resources:
            requests:
              memory: "384Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
