apiVersion: apps/v1
kind: Deployment
metadata:
  name: march-11-demo
  labels:
    backstage.io/kubernetes-id: march-11-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: march-11-demo
  template:
    metadata:
      labels:
        app: march-11-demo
        backstage.io/kubernetes-id: march-11-demo
    spec:
      containers:
        - name: march-11-demo
          image: chaitanyapandeygspann/march-11-demo:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000