apiVersion: v1
kind: Service
metadata:
  name: march-11-demo
spec:
  selector:
    app: march-11-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer


# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: march-11-demo-ingress
# spec:
#   ingressClassName: gce
#   rules:
#   - host: march-11-demo.example.com
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: march-11-demo
#             port:
#               number: 80
