apiVersion: v1
kind: Service
metadata:
  name: gssp-march-24
spec:
  selector:
    app: gssp-march-24
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer


# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: gssp-march-24-ingress
# spec:
#   ingressClassName: gce
#   rules:
#   - host: gssp-march-24.example.com
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: gssp-march-24
#             port:
#               number: 80
