apiVersion: apps/v1
kind: Deployment
metadata:
  name: rebase-28-apr
  labels:
    backstage.io/kubernetes-id: rebase-28-apr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rebase-28-apr
  template:
    metadata:
      labels:
        app: rebase-28-apr
        backstage.io/kubernetes-id: rebase-28-apr
    spec:
      containers:
        - name: rebase-28-apr
          image: chaitanyapandeygspann/rebase-28-apr:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000