apiVersion: apps/v1
kind: Deployment
metadata:
  name: dssp-sonarvault-testing-11
  labels:
    backstage.io/kubernetes-id: dssp-sonarvault-testing-11
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dssp-sonarvault-testing-11
  template:
    metadata:
      labels:
        app: dssp-sonarvault-testing-11
        backstage.io/kubernetes-id: dssp-sonarvault-testing-11
    spec:
      containers:
        - name: dssp-sonarvault-testing-11
          image: chaitanyapandeygspann/dssp-sonarvault-testing-11:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000