apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-test-23
  labels:
    backstage.io/kubernetes-id: demo-test-23
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-test-23
  template:
    metadata:
      labels:
        app: demo-test-23
        backstage.io/kubernetes-id: demo-test-23
    spec:
      containers:
        - name: demo-test-23
          image: ghcr.io/backstagessppoc/demo-test-23:8ae4a29808e86816a45b66ef96bcce4614ef314b
          imagePullPolicy: Always
          ports:
            - containerPort: 3000