apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-test-25
  labels:
    backstage.io/kubernetes-id: demo-test-25
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-test-25
  template:
    metadata:
      labels:
        app: demo-test-25
        backstage.io/kubernetes-id: demo-test-25
    spec:
      containers:
        - name: demo-test-25
          image: chaitanyapandeygspann/demo-test-25:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000