apiVersion: apps/v1
kind: Deployment
metadata:
  name: dssp-targetp-38
  namespace: dev
  labels:
    app: dssp-targetp-38
    backstage.io/kubernetes-id: dssp-targetp-38
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dssp-targetp-38
  template:
    metadata:
      labels:
        app: dssp-targetp-38
        backstage.io/kubernetes-id: dssp-targetp-38
        environment: dev
    spec:
      containers:
        - name: dssp-targetp-38
          image: chaitanyapandeygspann/dssp-targetp-38:1.0.7
          ports:
            - containerPort: 5000
          env:
            - name: APP_ENV
              value: "dev"
