apiVersion: apps/v1
kind: Deployment
metadata:
  name: dssp-test-apr-21-04
  labels:
    backstage.io/kubernetes-id: dssp-test-apr-21-04
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dssp-test-apr-21-04
  template:
    metadata:
      labels:
        app: dssp-test-apr-21-04
        backstage.io/kubernetes-id: dssp-test-apr-21-04
    spec:
      containers:
        - name: dssp-test-apr-21-04
          image: chaitanyapandeygspann/dssp-test-apr-21-04:1.0.3
          imagePullPolicy: Always
          ports:
            - containerPort: 3000