apiVersion: v1
kind: Service
metadata:
  name: centralized-sonar-vault-test-28-apr-01
spec:
  selector:
    app: centralized-sonar-vault-test-28-apr-01
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer


# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: centralized-sonar-vault-test-28-apr-01-ingress
# spec:
#   ingressClassName: gce
#   rules:
#   - host: centralized-sonar-vault-test-28-apr-01.example.com
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: centralized-sonar-vault-test-28-apr-01
#             port:
#               number: 80
