apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockercompose-testing
  labels:
    backstage.io/kubernetes-id: dockercompose-testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dockercompose-testing
  template:
    metadata:
      labels:
        app: dockercompose-testing
        backstage.io/kubernetes-id: dockercompose-testing
    spec:
      containers:
        - name: dockercompose-testing
          image: chaitanyapandeygspann/dockercompose-testing:1.0.3
          imagePullPolicy: Always
          ports:
            - containerPort: 3000