apiVersion: v1
kind: Service
metadata:
  name: testing-sonar-vault-27-apr-final
spec:
  selector:
    app: testing-sonar-vault-27-apr-final
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer


# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: testing-sonar-vault-27-apr-final-ingress
# spec:
#   ingressClassName: gce
#   rules:
#   - host: testing-sonar-vault-27-apr-final.example.com
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: testing-sonar-vault-27-apr-final
#             port:
#               number: 80