apiVersion: apps/v1
kind: Deployment
metadata:
  name: jsp-testing-2
  labels:
    backstage.io/kubernetes-id: jsp-testing-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jsp-testing-2
  template:
    metadata:
      labels:
        app: jsp-testing-2
        backstage.io/kubernetes-id: jsp-testing-2
    spec:
      containers:
        - name: jsp-testing-2
          image: chaitanyapandeygspann/jsp-testing-2:1.0.3
          imagePullPolicy: Always
          ports:
            - containerPort: 8080