apiVersion: apps/v1
kind: Deployment
metadata:
  name: dssp-apr-10-01
  labels:
    backstage.io/kubernetes-id: dssp-apr-10-01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dssp-apr-10-01
  template:
    metadata:
      labels:
        app: dssp-apr-10-01
        backstage.io/kubernetes-id: dssp-apr-10-01
    spec:
      containers:
        - name: dssp-apr-10-01
          image: chaitanyapandeygspann/dssp-apr-10-01:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000