apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-27apr-sonar-vault-testing
  labels:
    backstage.io/kubernetes-id: demo-27apr-sonar-vault-testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-27apr-sonar-vault-testing
  template:
    metadata:
      labels:
        app: demo-27apr-sonar-vault-testing
        backstage.io/kubernetes-id: demo-27apr-sonar-vault-testing
    spec:
      containers:
        - name: demo-27apr-sonar-vault-testing
          image: chaitanyapandeygspann/demo-27apr-sonar-vault-testing:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000