apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dssp-python-gitlab1
  namespace: dev
  labels:
    backstage.io/kubernetes-id: dssp-python-gitlab1
    environment: dev
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /dssp-python-gitlab1-dev
            pathType: Prefix
            backend:
              service:
                name: dssp-python-gitlab1
                port:
                  number: 80
