apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-ssp-march-16
  labels:
    backstage.io/kubernetes-id: demo-ssp-march-16
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-ssp-march-16
  template:
    metadata:
      labels:
        app: demo-ssp-march-16
        backstage.io/kubernetes-id: demo-ssp-march-16
    spec:
      containers:
        - name: demo-ssp-march-16
          image: chaitanyapandeygspann/demo-ssp-march-16:1.0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 3000