# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: dssp-targetnode-3
#   namespace: prod
#   labels:
#     app: dssp-targetnode-3
#     backstage.io/kubernetes-id: dssp-targetnode-3
#     environment: prod
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: dssp-targetnode-3
#   template:
#     metadata:
#       labels:
#         app: dssp-targetnode-3
#         backstage.io/kubernetes-id: dssp-targetnode-3
#         environment: prod
#     spec:
#       containers:
#         - name: dssp-targetnode-3
#           image: chaitanyapandeygspann/dssp-targetnode-3:1.0.7
#           ports:
#             - containerPort: 3000
#           env:
#             - name: APP_ENV
#               value: "prod"



apiVersion: apps/v1
kind: Deployment
metadata:
  name: dssp-targetnode-3
  namespace: prod
  labels:
    app: dssp-targetnode-3
    backstage.io/kubernetes-id: dssp-targetnode-3
    environment: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dssp-targetnode-3
  template:
    metadata:
      labels:
        app: dssp-targetnode-3
        backstage.io/kubernetes-id: dssp-targetnode-3
        environment: prod
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
    spec:
      containers:
        - name: dssp-targetnode-3
          image: chaitanyapandeygspann/dssp-targetnode-3:1.0.7
          ports:
            - containerPort: 3000
          env:
            - name: APP_ENV
              value: "prod"
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
              ephemeral-storage: "50Mi"
            limits:
              memory: "128Mi"
              cpu: "100m"
              ephemeral-storage: "100Mi"
