apiVersion: apps/v1
kind: Deployment
metadata:
  name: dgssp-test-docker
  labels:
    backstage.io/kubernetes-id: dgssp-test-docker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dgssp-test-docker
  template:
    metadata:
      labels:
        app: dgssp-test-docker
        backstage.io/kubernetes-id: dgssp-test-docker
    spec:
      containers:
        - name: dgssp-test-docker
          image: chaitanyapandeygspann/dgssp-test-docker:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000