apiVersion: v1
kind: Service
metadata:
  name: dgssp-test-docker
spec:
  selector:
    app: dgssp-test-docker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer


# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: dgssp-test-docker-ingress
# spec:
#   ingressClassName: gce
#   rules:
#   - host: dgssp-test-docker.example.com
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: dgssp-test-docker
#             port:
#               number: 80
