apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-march-12-1
  labels:
    backstage.io/kubernetes-id: demo-march-12-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-march-12-1
  template:
    metadata:
      labels:
        app: demo-march-12-1
        backstage.io/kubernetes-id: demo-march-12-1
    spec:
      containers:
        - name: demo-march-12-1
          image: ${DOCKER_IMAGE}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000