apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonar-vault-1
  labels:
    backstage.io/kubernetes-id: sonar-vault-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonar-vault-1
  template:
    metadata:
      labels:
        app: sonar-vault-1
        backstage.io/kubernetes-id: sonar-vault-1
    spec:
      containers:
        - name: sonar-vault-1
          image: chaitanyapandeygspann/sonar-vault-1:1.0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 3000