apiVersion: apps/v1
kind: Deployment
metadata:
  name: may-05-test-8
  labels:
    backstage.io/kubernetes-id: may-05-test-8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: may-05-test-8
  template:
    metadata:
      labels:
        app: may-05-test-8
        backstage.io/kubernetes-id: may-05-test-8
    spec:
      containers:
        - name: may-05-test-8
          image: ${DOCKER_IME}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
