apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dssp-targetp-23
  namespace: dev
  labels:
    backstage.io/kubernetes-id: dssp-targetp-23
    environment: dev
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx  
  rules:
    - http:
        paths:
          - path: /dssp-targetp-23-dev(/|$)(.*) 
            pathType: ImplementationSpecific
            backend:
              service:
                name: dssp-targetp-23
                port:
                  number: 80
