apiVersion: apps/v1
kind: Deployment
metadata:
  name: gssp-test-a4
  labels:
    backstage.io/kubernetes-id: gssp-test-a4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gssp-test-a4
  template:
    metadata:
      labels:
        app: gssp-test-a4
        backstage.io/kubernetes-id: gssp-test-a4
    spec:
      containers:
        - name: gssp-test-a4
          image: chaitanyapandeygspann/gssp-test-a4:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000