apiVersion: apps/v1
kind: Deployment
metadata:
  name: jsp-test1
  labels:
    backstage.io/kubernetes-id: jsp-test1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jsp-test1
  template:
    metadata:
      labels:
        app: jsp-test1
        backstage.io/kubernetes-id: jsp-test1
    spec:
      containers:
        - name: jsp-test1
          image: chaitanyapandeygspann/jsp-test1:1.0.3
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
