apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dssp-pythontest-1
  namespace: prod
  labels:
    backstage.io/kubernetes-id: dssp-pythontest-1
    environment: prod
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx  
  rules:
    - http:
        paths:
          - path: /dssp-pythontest-1-prod(/|$)(.*) 
            pathType: ImplementationSpecific
            backend:
              service:
                name: dssp-pythontest-1
                port:
                  number: 80
