apiVersion: apps/v1
kind: Deployment
metadata:
  name: gssp-gi-test-02-april
  labels:
    backstage.io/kubernetes-id: gssp-gi-test-02-april
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gssp-gi-test-02-april
  template:
    metadata:
      labels:
        app: gssp-gi-test-02-april
        backstage.io/kubernetes-id: gssp-gi-test-02-april
    spec:
      containers:
        - name: gssp-gi-test-02-april
          image: chaitanyapandeygspann/gssp-gi-test-02-april:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000