apiVersion: apps/v1
kind: Deployment
metadata:
  name: dssp-targetp-37
  namespace: dev
  labels:
    app: dssp-targetp-37
    backstage.io/kubernetes-id: dssp-targetp-37
    environment: dev
spec:
  replicas: 0
  selector:
    matchLabels:
      app: ${APP_NAE}
  template:
    metadata:
      labels:
        app: ${APP_NAE}
        backstage.io/kubernetes-id: dssp-targetp-37
        environment: dev
    spec:
      containers:
        - name: dssp-targetp-37
          image: chaitanyapandeygspann/dssp-targetp-37:1.0.12
          ports:
            - containerPort: ${APP_POT}
          env:
            - name: APP_ENV
              value: "dev"
