apiVersion: apps/v1
kind: Deployment
metadata:
  name: may-06-test-3
  labels:
    backstage.io/kubernetes-id: may-06-test-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: may-06-test-3
  template:
    metadata:
      labels:
        app: may-06-test-3
        backstage.io/kubernetes-id: may-06-test-3
    spec:
      containers:
        - name: may-06-test-3
          image: chaitanyapandeygspann/may-06-test-3:1.0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 3000