apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-test-19
  labels:
    backstage.io/kubernetes-id: demo-test-19
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-test-19
  template:
    metadata:
      labels:
        app: demo-test-19
        backstage.io/kubernetes-id: demo-test-19
    spec:
      containers:
        - name: demo-test-19
          image: ghcr.io/backstagessppoc/demo-test-19:9048d60e122ba4fed188bed23ef58e11ee2157f8
          imagePullPolicy: Always
          ports:
            - containerPort: 3000